### ISSUE TITLE
Suggest: arrow to navigate between previous/next block.

### ISSUE THREAD

**Issue by ivyfung1** [nemfoundation/nem2-explorer#100]
Suggest to have arrows for easy navigating previous and next block rather than go back to the previous page and click on the next block or edit the URL.

<img width="1060" alt="Screen Shot 2019-09-25 at 5 18 05 PM" src="https://user-images.githubusercontent.com/40448458/65587902-32754200-dfb9-11e9-875b-2116725dee0a.png">

**Comment by kumarnem** [comment]
Okay. @evias Any suggestion?
