### ISSUE TITLE
Suggestion: Rename of "Node" drop-down selection

### ISSUE THREAD

**Issue by ivyfung1** [nemfoundation/nem2-explorer#103]
Suggest to change "Node" to "Network Type/ Network Name" or "Generationhash" to reflect that those nodes could be from different network. 
Maybe Network:Node?
e.g. Mainnet:http://13.114.200.132:3000/

<img width="186" alt="Screen Shot 2019-09-26 at 2 30 23 PM" src="https://user-images.githubusercontent.com/40448458/65663802-69eff700-e06a-11e9-8931-a73a4ab954b3.png">

**Comment by evias** [comment]
hey there @ivyfung1 ; I would agree that there could be some information about the network name in the list.

But I think it is important to keep the node IPs there as this is the information that is relevant (which node is the explorer using to read the data I see.)
