### ISSUE TITLE
Don't put node settings floating in the middle of the mobile screen 

### ISSUE THREAD

**Issue by jabo38** [nemfoundation/nem2-explorer#117]
This doesn't look right. It can maybe be glued to the bottom, maybe fit in the top banner, or made to fit in much better with the other menu items, but just having it there doesn't look right. 

![image](https://user-images.githubusercontent.com/10395907/66244440-0f8c1180-e6ce-11e9-9a2d-7d03f60a5164.png)

Here are some suggestions. I don't know which one is best, but I guess I like the first one best. Regardless, any of them are better I think than how it is now.

**Comment by jabo38** [comment]
For instance, this one was done quite nice. 

![image](https://user-images.githubusercontent.com/10395907/66245169-ae663d00-e6d1-11e9-841f-a58760bfa61f.png)

**Comment by jabo38** [comment]
Here is another idea. Not sure what is best.

**Comment by jabo38** [comment]
This might be my favorite.

**Comment by jabo38** [comment]
At the min, we could at least do this.  
![image](https://user-images.githubusercontent.com/10395907/66245748-6e08be00-e6d5-11e9-8a35-267481f5108c.png)

**Comment by evias** [comment]
merged in master
