### ISSUE TITLE
Namespace detail shows `Child` instead of `Root`

### ISSUE THREAD

**Issue by evias** [nemfoundation/nem2-explorer#136]
As shown in following screenshot, the `nem` row should say `Root` namespace.

<img width="1242" alt="Screenshot 2019-10-15 at 12 06 11 PM" src="https://user-images.githubusercontent.com/141805/66822300-4373fc00-ef44-11e9-8d8c-fee998de2cef.png">

**Comment by evias** [comment]
Also please elaborate to explain what the `Status` field means

**Comment by evias** [comment]
@AnthonyLaw @OlegMakarenko

**Comment by AnthonyLaw** [comment]
namespace active `status` .
https://github.com/nemtech/nem2-sdk-typescript-javascript/blob/ee1aa81860ea5f453f479ea643e0529b040af61e/test/model/namespace/NamespaceInfo.spec.ts#L33

maybe i should change it to `Active` instead of `Status`
