### ISSUE TITLE
Don't Statically Initialize SDK HTTP Classes

### ISSUE THREAD

**Issue by Alexhuszagh** [nemfoundation/nem2-explorer#152]
In SDK routes like `getBlock`, we do:

```js
class sdkBlock {
  static init = async nodeUrl => {
    NODE_URL = nodeUrl
    CHAIN_HTTP = new ChainHttp(nodeUrl)
    BLOCK_HTTP = new BlockHttp(nodeUrl)
    NETWORK_HTTP = new NetworkHttp(nodeUrl)
  }
```

This means that we have a global, static variable set to a single endpoint. This means we will not respect any endpoint changes. The routes are lightweight wrappers around the endpoints, and we should create them on-the-fly.

**Comment by evias** [comment]
merged in master
