### ISSUE TITLE
Page break in Production build, if just click on URL with params. 

### ISSUE THREAD

**Issue by AnthonyLaw** [nemfoundation/nem2-explorer#160]
If you visit from main page, then go to transaction page, step by step, it's working fine.

But when you copy the URL and paste to browser, it show `page not found`
example: http://3.225.39.54/transaction/69b462dc36abe594b93eca317dc6a6c087edaaf216e57b828b553924add921d1 (page not found)

**Comment by OlegMakarenko** [comment]
**Nginx configuration issue** 

Add to nging config:
```
location / {
  try_files $uri $uri/ /index.html;
}
```

**Comment by AnthonyLaw** [comment]
@kaiyzen @evias

**Comment by kaiyzen** [comment]
was missing the /index.html, @OlegMakarenko @AnthonyLaw give another try to verify and if fine can close out

**Comment by AnthonyLaw** [comment]
It's working! :)
