### ISSUE TITLE
Mosaic Detail page does not work

### ISSUE THREAD

**Issue by OlegMakarenko** [nemfoundation/nem2-explorer#174]
**Expected Behaviour**
Table should show info about requested mosaic

**Actual Behaviour**
- Message: "Nothing to show.."

- Call of nonexistent method at 
`src/store/mosaic.js` ->
`fetchMosaicInfo()` -> 
`sdkMosaic.`**getMosaicInfo()**

**Environment**

http://explorer.mt.nemtech.network/mosaic/308f144790cd7bc4

**Comment by AnthonyLaw** [comment]
It was working, but @Alexhuszagh comment the source code.

https://github.com/nemfoundation/nem2-explorer/commit/db1465a0b0e9e624260fd24629e55384912e6ea0#diff-f7c56712c055278881f11dff14832792R54

**Comment by evias** [comment]
merged in master
