### ISSUE TITLE
center "terms and privacy"

### ISSUE THREAD

**Issue by jabo38** [nemfoundation/nem2-explorer#183]
If we are going to put "terms and privacy" on the bottom, please keep it centered with the rest of the content on the bottom.  mockup is below. 

![image](https://user-images.githubusercontent.com/10395907/67984347-8399d680-fbf4-11e9-9db2-98e7b683a732.png)

**Comment by jabo38** [comment]
Probably best to just say the following:

**Comment by jomongeorge** [comment]
Deployed here http://3.17.139.170:8090/

**Comment by jabo38** [comment]
That is good but probably write "Terms & Privacy" instead of "Terms   &   Privacy"

**Comment by jomongeorge** [comment]
changes made.
Deployed here http://3.17.139.170:8090/

**Comment by evias** [comment]
merged in master

**Comment by jabo38** [comment]
I think this needs to be reviewed because for instance the space between "Nem.io" and "Foundation" is way smaller than the spaces around the "&" sign.
