### ISSUE TITLE
Netlify build keeps loading forever

### ISSUE THREAD

**Issue by dgarcia360** [nemfoundation/nem2-explorer#197]
The explorer build deployed in [netlify](https://nem2-explorer.netlify.com/
) does not reach catapult-rest.

![image](https://user-images.githubusercontent.com/9107969/68111619-724c1500-fee7-11e9-8cc8-b7381df0deee.png)

**Comment by AnthonyLaw** [comment]
it's `Https` endpoint issue.
Nate will deploy some endpoint with `Https`
