### ISSUE TITLE
Account Details component namespace list is empty

### ISSUE THREAD

**Issue by evias** [nemfoundation/nem2-explorer#198]
reference: http://explorer.mt.nemtech.network/account/sacyzjllp6ocy3kf3ttjrve4w3mlnp5bqp75nkjc

API: http://api-01.mt.eu-central-1.nemtech.network:3000/account/SACYZJLLP6OCY3KF3TTJRVE4W3MLNP5BQP75NKJC/namespaces

**Comment by AnthonyLaw** [comment]
@evias  I found out it seem API server site issue.

http://api-01.mt.eu-central-1.nemtech.network:3000/account/SACYZJLLP6OCY3KF3TTJRVE4W3MLNP5BQP75NKJC/namespaces

Return are missing one of the namespace object (root namespace)

check on the namespace ID : http://api-01.mt.eu-central-1.nemtech.network:3000/namespace/AADE8BE973921744

**Comment by AnthonyLaw** [comment]
[reported in Catapult rest](https://github.com/nemtech/catapult-rest/issues/192)

**Comment by AnthonyLaw** [comment]
Solved in Catapult Rest
