### ISSUE TITLE
ID field of Namespace listing contains wrong information and column changes

### ISSUE THREAD

**Issue by evias** [nemfoundation/nem2-explorer#200]
http://explorer.mt.nemtech.network/namespaces

The first column of this table doesn't contain valid namespace id.

Actionable Items:

- Fix namespace id column content
- Add `registration type` column with either `Root` or `Sub`
- Remove `0000000` parent ids and display `N/A` for example

**Comment by dgarcia360** [comment]
![image](https://user-images.githubusercontent.com/9107969/68121123-e0500680-fefe-11e9-9b79-d44e9e6697dc.png)

The status column states "true", but it should be "active"?

**Comment by dgarcia360** [comment]
![image](https://user-images.githubusercontent.com/9107969/68121221-17261c80-feff-11e9-9eee-d1d0e180a826.png)

End-height Infinity -> Never?

**Comment by AnthonyLaw** [comment]
> ![image](https://user-images.githubusercontent.com/9107969/68121123-e0500680-fefe-11e9-9b79-d44e9e6697dc.png)
> 
> The status column states "true", but it should be "active"?

what you think if change the `status` to `Active` ?

**Comment by AnthonyLaw** [comment]
> ![image](https://user-images.githubusercontent.com/9107969/68121221-17261c80-feff-11e9-9eee-d1d0e180a826.png)
> 
> End-height Infinity -> Never?

I found some logic error, thanks for report 👍
