### ISSUE TITLE
wording Multsig

### ISSUE THREAD

**Issue by decentraliser** [nemfoundation/nem2-explorer#218]
https://github.com/nemfoundation/nem2-explorer/blob/12257379f16f10001b031391b10e5625c5ce0ba4/src/views/AccountDetail.vue#L16

there is a Multsig Cosignatories also

**Comment by Alexhuszagh** [comment]
@decentraliser This should have been patched with cf11fd3766ef0e68f90ea58a5481bf60a9958fe5#diff-5b82eb4ce013918672c32282e0e28de9
