### ISSUE TITLE
`isMobile` is duplicated.

### ISSUE THREAD

**Issue by Alexhuszagh** [nemfoundation/nem2-explorer#227]
`isMobile` is duplicated identically in both:
- helper.js
- ui.js

Should only be present in `helper.js` or `ui.js`. If it's needed in `ui.js`, it should remove the `helper.js` implementation, rather than duplicate the entire code.

In addition, the `ui.js` implementation is missing various bug fixes to force mobile mode on Chrome developer tools, and therefore is insufficient.

**Comment by Alexhuszagh** [comment]
Actually, we don't even seem to use `isMobile` anymore. Can @OlegMakarenko or @AnthonyLaw chime into this?

**Comment by Alexhuszagh** [comment]
Not a surprise: the mobile menu is entirely broken.

![Screenshot_20191113_111000](https://user-images.githubusercontent.com/9440903/68786889-2b0c0580-0606-11ea-86c5-0f4cc06fe15f.png)

**Comment by AnthonyLaw** [comment]
Yes, we should Remove `isMobile`

**Comment by Alexhuszagh** [comment]
@AnthonyLaw Perfect, will do now.

**Comment by AnthonyLaw** [comment]
fixed in master
