### ISSUE TITLE
Node selector is not appear if peers-api.json includes "localhost"

### ISSUE THREAD

**Issue by 44uk** [nemfoundation/nem2-explorer#256]
<img width="451" alt="スクリーンショット 2019-11-25 22 31 40" src="https://user-images.githubusercontent.com/370508/69544646-7ee9f780-0fd3-11ea-930f-23b788dc1fee.png">

**Comment by evias** [comment]
@AnthonyLaw can you try to reproduce and report here? 

Thanks @44uk :+1:

**Comment by AnthonyLaw** [comment]
https://github.com/nemfoundation/nem2-explorer/blob/70b8a4a42b6c5cb3593045117eb543435b67bc76/src/helper.js#L54

Ohh, I found the issue, because in the validURL checker return 'http://localhost.com:3000'  is not valid.

will fix this in next PR

**Comment by evias** [comment]
`localhost.com` is not valid ; but `localhost:3000` should work
