### ISSUE TITLE
Block age and time stamps are off

### ISSUE THREAD

**Issue by kaiyzen** [nemfoundation/nem2-explorer#270]
Seems possible regression related to 0.9.1.1 or other issue with experimental branch, block age and timestamp isnt showing correctly:

http://explorer.nemtech.network/blocks

**Comment by kaiyzen** [comment]
looks like with latest build from about 3hrs ago things are fixed up some, timestamps are looking correct, the age instead of 3yrs seems to show 1hr for all currently

**Comment by AnthonyLaw** [comment]
fixed in master
