### ISSUE TITLE
Unable to show Aggregate Complete transaction detail

### ISSUE THREAD

**Issue by OlegMakarenko** [nemfoundation/nem2-explorer#288]
[Aggregate Complete](http://api-harvest-20.eu-west-1.nemtech.network:3000/transaction/2972B07F3BAE981E4EA94BCDC03DD711C5FEE06466364511729AB52CF988098E) transaction shows as nonexistent

**Environment**
http://explorer.nemtech.network/transaction/2972B07F3BAE981E4EA94BCDC03DD711C5FEE06466364511729AB52CF988098E

**Comment by AnthonyLaw** [comment]
The reason is because `getTransactionEffectiveFee` throw error when the tranasction type is `MosaicDefinitionTransaction` and `MosaicSupplyChangeTransaction`

Issue related https://github.com/nemtech/catapult-rest/issues/242

I temporary replace in MaxFees.

**Comment by Vektrat** [comment]
problem lies in openapi mismatch that ends up affecting sdks:

https://github.com/nemtech/symbol-openapi/issues/85
