### ISSUE TITLE
Transaction hash not found: no message returned in the UI

### ISSUE THREAD

**Issue by decentraliser** [nemfoundation/nem2-explorer#293]
http://explorer.nemtech.network/transaction/957CE82EE28B330F22DBCACFA81E45E5C865DC7FB6F292A61AE8860BE972C0BC

IIRC there was a red message before when an unknown transaction has was input in the search bar, now there is nothing

![image](https://user-images.githubusercontent.com/36499647/72695872-1a7f8a80-3b75-11ea-91c7-c56ec9d59d37.png)

**Comment by AnthonyLaw** [comment]
it's working in Master branch.
