### ISSUE TITLE
[Task] Account Page Missing data filed

### ISSUE THREAD

**Issue by AnthonyLaw** [nemfoundation/nem2-explorer#49]
### Account Page
- Namespaces aliases with Account
- Multisig account status and detail.

**Comment by AnthonyLaw** [comment]
Namespace aliases with Account is break in Current `"nem2-sdk": "^0.13.1"`

```
const addressObj = Address.createFromRawAddress(address)
  const accountsNames = await accountHttp
    .getAccountsNames([addressObj])
    .toPromise()
```

Error: `Uncaught (in promise) TypeError: Cannot read property 'length' of undefined`

**Comment by evias** [comment]
@OlegMakarenko missing multisig information in this page for example: http://explorer.mt.nemtech.network/account/sb2y5gyp6hpibmhejl6crjdxdsebggmdtulamewn

this is for address: `SB2Y5GYP6HPIBMHEJL6CRJDXDSEBGGMDTULAMEWN`

Network information: http://api-01.mt.eu-central-1.nemtech.network:3000/account/SB2Y5GYP6HPIBMHEJL6CRJDXDSEBGGMDTULAMEWN/multisig

**Comment by AnthonyLaw** [comment]
I'm working it halfway, maybe i can disucss with oleg more :)
