### ISSUE TITLE
Price/Market Cap/Total Tx/Block Height bar glued to one above it. 

### ISSUE THREAD

**Issue by jabo38** [nemfoundation/nem2-explorer#54]
It should be one box or two boxes separated with space. Having the shadow immediately join two boxes is strange. 

![image](https://user-images.githubusercontent.com/10395907/64734830-03d17480-d4ad-11e9-922c-ee87878aa12c.png)

**Comment by jomongeorge** [comment]
I used the shadow to separate the graph and the information section, to give an effect bottom section( slide from the graph part. 
Now changed to the following style, what you think about it ??

![image](https://user-images.githubusercontent.com/5396869/64756479-c0c6de00-d54c-11e9-8cd5-1ed88b823684.png)
