### ISSUE TITLE
List time of latest blocks in most recent time, not cumulative. 

### ISSUE THREAD

**Issue by jabo38** [nemfoundation/nem2-explorer#55]
Blocks say "-17986 seconds ago" and "-17971 seconds ago". It should say "-15 seconds" and "-29 seconds ago" and so on. 

![image](https://user-images.githubusercontent.com/10395907/64735154-9bcf5e00-d4ad-11e9-8f1e-cd0a394b4d84.png)

**Comment by jabo38** [comment]
Same applies when on the Blocks page. 

![image](https://user-images.githubusercontent.com/10395907/64735765-d5ed2f80-d4ae-11e9-8c82-3ec0eb84afaa.png)

**Comment by AnthonyLaw** [comment]
it's weird, just wonder your computer is in correct date-time?

**Comment by Alexhuszagh** [comment]
@jabo38 This might require changing the date to use the local time when formatting the block:

```diff
diff --git a/client/src/format.js b/client/src/format.js
index ac9c49e..e275af7 100644
--- a/client/src/format.js
+++ b/client/src/format.js
@@ -43,9 +43,9 @@ const formatBlock = (block) => {
     height: block.height.compact(),
     hash: block.hash,
     timestamp: block.timestamp.compact() / 1000 + 1459468800,
-    date: moment(
+    date: moment.utc(
       (block.timestamp.compact() / 1000 + 1459468800) * 1000
-    ).format('YYYY-MM-DD HH:mm:ss'),
+    ).local().format('YYYY-MM-DD HH:mm:ss'),
     totalFee: block.totalFee.compact(),
     difficulty: (block.difficulty.compact() / 1000000000000).toFixed(2),
     numTransactions: block.numTransactions ? block.numTransactions : 0,
```

**Comment by Alexhuszagh** [comment]
@jabo38 I believe this would be fixed in the following commit:
https://github.com/Alexhuszagh/nf-catapult-explorer/commit/2fdfa0345972c3ecc8a4717917852b4cde25b14f
