### ISSUE TITLE
Mosaics page doesn't work 

### ISSUE THREAD

**Issue by jabo38** [nemfoundation/nem2-explorer#58]
Shows mockup data

**Comment by Alexhuszagh** [comment]
I believe we should take this in a multi-step approach:

1. Move mockup data to use a hard-coded array of NEM SDK MosaicInfo objects.
2. Implement the upstream REST and SDK APIs required on a fork.
3. Get data in terms of that fork.
4. Merge fork with PR into the base repositories.
