### ISSUE TITLE
Code consistency fixes

### ISSUE THREAD

**Issue by evias** [nemfoundation/nem2-explorer#71]
Several points have been observed in the source code that can be improved to favorise code consistency.

- Files under components should be named with **camel case**. Example: PageFooter, PageMenu, WidgetX, etc.

- Components must not query external URLs directly, a Service class must be provided to avoid components source code complexity. Example: https://github.com/nemfoundation/nem2-explorer/blob/master/client/src/components/nempricegraph.vue#L86

- ApexGraph integration is using _pure javascript_ integration, can be made with Vue as well. @OlegMakarenko please elaborate solution proposal in comment.

- Store mutations and general store structure must be improved, will be hard to maintain with many different data points: https://github.com/nemfoundation/nem2-explorer/blob/master/client/src/store.js#L43

**Comment by OlegMakarenko** [comment]
> ApexGraph integration is using pure javascript integration, can be made with Vue as well. @OlegMakarenko please elaborate solution proposal in comment

There is ApexChart package for Vue: https://github.com/apexcharts/vue-apexcharts
