### ISSUE TITLE
Dynamic Table Data is Poorly Aligned

### ISSUE THREAD

**Issue by Alexhuszagh** [nemfoundation/nem2-explorer#83]
Sample view as of c02f8a8914b5caedd03b958274da6773ac7df925. Notice how "Type" is poorly aligned with the data in its column.

![Screenshot_20190918_171112](https://user-images.githubusercontent.com/9440903/65189718-62f83180-da37-11e9-9848-81902e0d7273.png)

**Comment by jomongeorge** [comment]
remove id table-block-list from the table element property. It will fix the issue
